//! Well-known BACnet enumeration types for use at the service layer.
//!
//! These enumerations are not part of the wire codec (which uses raw integers),
//! but provide named constants for Rust and Python consumers of the library.

use std::fmt;

// ─────────────────────────────────────────────────────────────────────────────
// PropertyIdentifier
// ─────────────────────────────────────────────────────────────────────────────

/// Standard BACnet property identifiers (clause 12.4 of the BACnet standard).
///
/// Use `PropertyIdentifier::from(u32)` to convert a raw wire value.
/// Unknown or proprietary values are wrapped in `Unknown(u32)` rather than
/// causing a panic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PropertyIdentifier {
    AckedTransitions,
    AckRequired,
    Action,
    ActionText,
    ActiveText,
    ActiveVtSessions,
    AlarmValue,
    AlarmValues,
    All,
    AllWritesSuccessful,
    ApduSegmentTimeout,
    ApduTimeout,
    ApplicationSoftwareVersion,
    Archive,
    Bias,
    ChangeOfStateCount,
    ChangeOfStateTime,
    NotificationClass,
    Deadband,
    DerivativeConstant,
    DerivativeConstantUnits,
    Description,
    DescriptionOfHalt,
    DeviceAddressBinding,
    DeviceType,
    EffectivePeriod,
    ElapsedActiveTime,
    ErrorLimit,
    EventEnable,
    EventState,
    EventType,
    ExceptionSchedule,
    FaultValues,
    FeedbackValue,
    FileAccessMethod,
    FileSize,
    FileType,
    FirmwareRevision,
    HighLimit,
    InactiveText,
    InProcess,
    InstanceOf,
    IntegralConstant,
    IntegralConstantUnits,
    LimitEnable,
    ListOfGroupMembers,
    ListOfObjectPropertyReferences,
    ListOfSessionKeys,
    LocalDate,
    LocalTime,
    Location,
    LowLimit,
    ManipulatedVariableReference,
    MaximumOutput,
    MaxApduLengthAccepted,
    MaxInfoFrames,
    MaxMaster,
    MaxPresValue,
    MinimumOffTime,
    MinimumOnTime,
    MinimumOutput,
    MinPresValue,
    ModelName,
    ModificationDate,
    NotifyType,
    NumberOfApduRetries,
    NumberOfStates,
    ObjectIdentifier,
    ObjectList,
    ObjectName,
    ObjectPropertyReference,
    ObjectType,
    Optional,
    OutOfService,
    OutputUnits,
    EventParameters,
    Polarity,
    PresentValue,
    Priority,
    PriorityArray,
    PriorityForWriting,
    ProcessIdentifier,
    ProgramChange,
    ProgramLocation,
    ProgramState,
    ProportionalConstant,
    ProportionalConstantUnits,
    ProtocolObjectTypesSupported,
    ProtocolServicesSupported,
    ProtocolVersion,
    ReadOnly,
    ReasonForHalt,
    Recipient,
    RecipientList,
    Reliability,
    RelinquishDefault,
    Required,
    Resolution,
    SegmentationSupported,
    Setpoint,
    SetpointReference,
    StateText,
    StatusFlags,
    SystemStatus,
    TimeDelay,
    TimeOfActiveTimeReset,
    TimeOfStateCountReset,
    TimeSynchronizationRecipients,
    Units,
    UpdateInterval,
    UtcOffset,
    VendorIdentifier,
    VendorName,
    VtClassesSupported,
    WeeklySchedule,
    AttemptedSamples,
    AverageValue,
    BufferSize,
    ClientCovIncrement,
    CovResubscriptionInterval,
    CurrentNotifyTime,
    EventTimeStamps,
    LogBuffer,
    LogDeviceObjectProperty,
    Enable,
    LogInterval,
    MaximumValue,
    MinimumValue,
    NotificationThreshold,
    PreviousNotifyTime,
    ProfileName,
    RecordCount,
    RecordsSinceNotification,
    StartTime,
    StopTime,
    StopWhenFull,
    TotalRecordCount,
    ValidSamples,
    WindowInterval,
    WindowSamples,
    MaximumValueTimestamp,
    MinimumValueTimestamp,
    Variance,
    ActiveCovSubscriptions,
    BackupFailureTimeout,
    ConfigurationFiles,
    DatabaseRevision,
    DirectReading,
    LastRestoreTime,
    MaintenanceRequired,
    MemberOf,
    Mode,
    OperationExpected,
    Setting,
    Silenced,
    TrackingValue,
    ZoneMembers,
    LifeSafetyAlarmValues,
    MaxSegmentsAccepted,
    ProfileLocation,
    AutoSlaveDiscovery,
    ManualSlaveAddressBinding,
    SlaveAddressBinding,
    SlaveProxyEnable,
    LastNotifyRecord,
    ScheduleDefault,
    AcceptedModes,
    AdjustValue,
    Count,
    CountBeforeChange,
    CountChangeTime,
    CovPeriod,
    InputReference,
    LimitMonitoringInterval,
    LoggingObject,
    LoggingRecord,
    Prescale,
    PulseRate,
    Scale,
    ScaleFactor,
    UpdateTime,
    ValueBeforeChange,
    ValueSet,
    ValueChangeTime,
    AlignIntervals,
    IntervalOffset,
    LastRestartReason,
    LoggingType,
    RestartNotificationRecipients,
    TimeOfDeviceRestart,
    TimeSynchronizationInterval,
    Trigger,
    UtcTimeSynchronizationRecipients,
    NodeSubtype,
    NodeType,
    StructuredObjectList,
    SubordinateAnnotations,
    SubordinateList,
    ActualShedLevel,
    DutyWindow,
    ExpectedShedLevel,
    FullDutyBaseline,
    RequestedShedLevel,
    ShedDuration,
    ShedLevelDescriptions,
    ShedLevels,
    StateDescription,
    DoorAlarmState,
    DoorExtendedPulseTime,
    DoorMembers,
    DoorOpenTooLongTime,
    DoorPulseTime,
    DoorStatus,
    DoorUnlockDelayTime,
    LockStatus,
    MaskedAlarmValues,
    SecuredAccess,
    AbsenteeLimit,
    AccessAlarmEvents,
    AccessDoors,
    AccessEvent,
    AccessEventAuthenticationFactor,
    AccessEventCredential,
    AccessEventTime,
    AccessTransactionEvents,
    Accompaniment,
    AccompanimentTime,
    ActivationTime,
    ActiveAuthenticationPolicy,
    AssignedAccessRights,
    AuthenticationFactors,
    AuthenticationPolicyList,
    AuthenticationPolicyNames,
    AuthenticationStatus,
    AuthorizationMode,
    BelongsTo,
    CredentialDisable,
    CredentialStatus,
    Credentials,
    CredentialsInZone,
    DaysRemaining,
    EntryPoints,
    ExitPoints,
    ExpiryTime,
    ExtendedTimeEnable,
    FailedAttemptEvents,
    FailedAttempts,
    FailedAttemptsTime,
    LastAccessEvent,
    LastAccessPoint,
    LastCredentialAdded,
    LastCredentialAddedTime,
    LastCredentialRemoved,
    LastCredentialRemovedTime,
    LastUseTime,
    Lockout,
    LockoutRelinquishTime,
    MasterExemption,
    MaxFailedAttempts,
    Members,
    MemberOf2,
    NegativeAccessRules,
    NumberOfAuthenticationPolicies,
    OccupancyCount,
    OccupancyCountAdjust,
    OccupancyCountEnable,
    OccupancyExemption,
    OccupancyLowerLimit,
    OccupancyLowerLimitEnforced,
    OccupancyState,
    OccupancyUpperLimit,
    OccupancyUpperLimitEnforced,
    PassbackExemption,
    PassbackMode,
    PassbackTimeout,
    PositiveAccessRules,
    ReasonForDisable,
    SupportedFormats,
    SupportedFormatClasses,
    ThreatAuthority,
    ThreatLevel,
    TraceFlag,
    TransactionNotificationClass,
    UserExternalIdentifier,
    UserInformationReference,
    UserName,
    UserType,
    UsesRemaining,
    ZoneFrom,
    ZoneTo,
    AccessEventTag,
    GlobalIdentifier,
    VerificationTime,
    BaseDeviceSecurityPolicy,
    DistributionKeyRevision,
    DoNotHide,
    KeySets,
    LastKeyServer,
    NetworkAccessSecurityPolicies,
    PacketReorderTime,
    SecurityPduTimeout,
    SecurityTimeWindow,
    SupportedSecurityAlgorithm,
    UpdateKeySetTimeout,
    BackupAndRestoreState,
    BackupPreparationTime,
    RestoreCompletionTime,
    RestorePreparationTime,
    BitMask,
    BitText,
    IsUtc,
    GroupMembers,
    GroupMemberNames,
    MemberStatusFlags,
    RequestedUpdateInterval,
    Resolution2,
    CovuPeriod,
    CovuRecipients,
    EventMessageTexts,
    EventMessageTextsConfig,
    EventDetectionEnable,
    EventAlgorithmInhibit,
    EventAlgorithmInhibitRef,
    TimeDelayNormal,
    ReliabilityEvaluationInhibit,
    FaultParameters,
    FaultType,
    LocalForwardingOnly,
    ProcessIdentifierFilter,
    SubscribedRecipients,
    PortFilter,
    AuthorizationExemptions,
    AllowGroupDelayInhibit,
    ChannelNumber,
    ControlGroups,
    ExecutionDelay,
    LastPriority,
    WriteStatus,
    PropertyList,
    SerialNumber,
    BlinkWarnEnable,
    DefaultFadeTime,
    DefaultRampRate,
    DefaultStepIncrement,
    EgressActive,
    EgressTime,
    InProgress,
    InstantianeousPower,
    LightingCommand,
    LightingCommandDefaultPriority,
    MaxActualValue,
    MinActualValue,
    Power,
    Transition,
    Unknown(u32),
}

impl From<u32> for PropertyIdentifier {
    fn from(value: u32) -> Self {
        match value {
            0 => PropertyIdentifier::AckedTransitions,
            1 => PropertyIdentifier::AckRequired,
            2 => PropertyIdentifier::Action,
            3 => PropertyIdentifier::ActionText,
            4 => PropertyIdentifier::ActiveText,
            5 => PropertyIdentifier::ActiveVtSessions,
            6 => PropertyIdentifier::AlarmValue,
            7 => PropertyIdentifier::AlarmValues,
            8 => PropertyIdentifier::All,
            9 => PropertyIdentifier::AllWritesSuccessful,
            10 => PropertyIdentifier::ApduSegmentTimeout,
            11 => PropertyIdentifier::ApduTimeout,
            12 => PropertyIdentifier::ApplicationSoftwareVersion,
            13 => PropertyIdentifier::Archive,
            14 => PropertyIdentifier::Bias,
            15 => PropertyIdentifier::ChangeOfStateCount,
            16 => PropertyIdentifier::ChangeOfStateTime,
            17 => PropertyIdentifier::NotificationClass,
            19 => PropertyIdentifier::Deadband,
            20 => PropertyIdentifier::DerivativeConstant,
            21 => PropertyIdentifier::DerivativeConstantUnits,
            28 => PropertyIdentifier::Description,
            29 => PropertyIdentifier::DescriptionOfHalt,
            30 => PropertyIdentifier::DeviceAddressBinding,
            31 => PropertyIdentifier::DeviceType,
            32 => PropertyIdentifier::EffectivePeriod,
            33 => PropertyIdentifier::ElapsedActiveTime,
            34 => PropertyIdentifier::ErrorLimit,
            35 => PropertyIdentifier::EventEnable,
            36 => PropertyIdentifier::EventState,
            37 => PropertyIdentifier::EventType,
            38 => PropertyIdentifier::ExceptionSchedule,
            39 => PropertyIdentifier::FaultValues,
            40 => PropertyIdentifier::FeedbackValue,
            41 => PropertyIdentifier::FileAccessMethod,
            42 => PropertyIdentifier::FileSize,
            43 => PropertyIdentifier::FileType,
            44 => PropertyIdentifier::FirmwareRevision,
            45 => PropertyIdentifier::HighLimit,
            46 => PropertyIdentifier::InactiveText,
            47 => PropertyIdentifier::InProcess,
            48 => PropertyIdentifier::InstanceOf,
            49 => PropertyIdentifier::IntegralConstant,
            50 => PropertyIdentifier::IntegralConstantUnits,
            52 => PropertyIdentifier::LimitEnable,
            53 => PropertyIdentifier::ListOfGroupMembers,
            54 => PropertyIdentifier::ListOfObjectPropertyReferences,
            55 => PropertyIdentifier::ListOfSessionKeys,
            56 => PropertyIdentifier::LocalDate,
            57 => PropertyIdentifier::LocalTime,
            58 => PropertyIdentifier::Location,
            59 => PropertyIdentifier::LowLimit,
            60 => PropertyIdentifier::ManipulatedVariableReference,
            61 => PropertyIdentifier::MaximumOutput,
            62 => PropertyIdentifier::MaxApduLengthAccepted,
            63 => PropertyIdentifier::MaxInfoFrames,
            64 => PropertyIdentifier::MaxMaster,
            65 => PropertyIdentifier::MaxPresValue,
            66 => PropertyIdentifier::MinimumOffTime,
            67 => PropertyIdentifier::MinimumOnTime,
            68 => PropertyIdentifier::MinimumOutput,
            69 => PropertyIdentifier::MinPresValue,
            70 => PropertyIdentifier::ModelName,
            71 => PropertyIdentifier::ModificationDate,
            72 => PropertyIdentifier::NotifyType,
            73 => PropertyIdentifier::NumberOfApduRetries,
            74 => PropertyIdentifier::NumberOfStates,
            75 => PropertyIdentifier::ObjectIdentifier,
            76 => PropertyIdentifier::ObjectList,
            77 => PropertyIdentifier::ObjectName,
            78 => PropertyIdentifier::ObjectPropertyReference,
            79 => PropertyIdentifier::ObjectType,
            80 => PropertyIdentifier::Optional,
            81 => PropertyIdentifier::OutOfService,
            82 => PropertyIdentifier::OutputUnits,
            83 => PropertyIdentifier::EventParameters,
            84 => PropertyIdentifier::Polarity,
            85 => PropertyIdentifier::PresentValue,
            86 => PropertyIdentifier::Priority,
            87 => PropertyIdentifier::PriorityArray,
            88 => PropertyIdentifier::PriorityForWriting,
            89 => PropertyIdentifier::ProcessIdentifier,
            90 => PropertyIdentifier::ProgramChange,
            91 => PropertyIdentifier::ProgramLocation,
            92 => PropertyIdentifier::ProgramState,
            93 => PropertyIdentifier::ProportionalConstant,
            94 => PropertyIdentifier::ProportionalConstantUnits,
            96 => PropertyIdentifier::ProtocolObjectTypesSupported,
            97 => PropertyIdentifier::ProtocolServicesSupported,
            98 => PropertyIdentifier::ProtocolVersion,
            99 => PropertyIdentifier::ReadOnly,
            100 => PropertyIdentifier::ReasonForHalt,
            101 => PropertyIdentifier::Recipient,
            102 => PropertyIdentifier::RecipientList,
            103 => PropertyIdentifier::Reliability,
            104 => PropertyIdentifier::RelinquishDefault,
            105 => PropertyIdentifier::Required,
            106 => PropertyIdentifier::Resolution,
            107 => PropertyIdentifier::SegmentationSupported,
            108 => PropertyIdentifier::Setpoint,
            109 => PropertyIdentifier::SetpointReference,
            110 => PropertyIdentifier::StateText,
            111 => PropertyIdentifier::StatusFlags,
            112 => PropertyIdentifier::SystemStatus,
            113 => PropertyIdentifier::TimeDelay,
            114 => PropertyIdentifier::TimeOfActiveTimeReset,
            115 => PropertyIdentifier::TimeOfStateCountReset,
            116 => PropertyIdentifier::TimeSynchronizationRecipients,
            117 => PropertyIdentifier::Units,
            118 => PropertyIdentifier::UpdateInterval,
            119 => PropertyIdentifier::UtcOffset,
            120 => PropertyIdentifier::VendorIdentifier,
            121 => PropertyIdentifier::VendorName,
            122 => PropertyIdentifier::VtClassesSupported,
            123 => PropertyIdentifier::WeeklySchedule,
            124 => PropertyIdentifier::AttemptedSamples,
            125 => PropertyIdentifier::AverageValue,
            126 => PropertyIdentifier::BufferSize,
            127 => PropertyIdentifier::ClientCovIncrement,
            128 => PropertyIdentifier::CovResubscriptionInterval,
            129 => PropertyIdentifier::CurrentNotifyTime,
            130 => PropertyIdentifier::EventTimeStamps,
            131 => PropertyIdentifier::LogBuffer,
            132 => PropertyIdentifier::LogDeviceObjectProperty,
            133 => PropertyIdentifier::Enable,
            134 => PropertyIdentifier::LogInterval,
            135 => PropertyIdentifier::MaximumValue,
            136 => PropertyIdentifier::MinimumValue,
            137 => PropertyIdentifier::NotificationThreshold,
            138 => PropertyIdentifier::PreviousNotifyTime,
            139 => PropertyIdentifier::ProfileName,
            140 => PropertyIdentifier::RecordCount,
            141 => PropertyIdentifier::RecordsSinceNotification,
            142 => PropertyIdentifier::StartTime,
            143 => PropertyIdentifier::StopTime,
            144 => PropertyIdentifier::StopWhenFull,
            145 => PropertyIdentifier::TotalRecordCount,
            146 => PropertyIdentifier::ValidSamples,
            147 => PropertyIdentifier::WindowInterval,
            148 => PropertyIdentifier::WindowSamples,
            149 => PropertyIdentifier::MaximumValueTimestamp,
            150 => PropertyIdentifier::MinimumValueTimestamp,
            151 => PropertyIdentifier::Variance,
            152 => PropertyIdentifier::ActiveCovSubscriptions,
            153 => PropertyIdentifier::BackupFailureTimeout,
            154 => PropertyIdentifier::ConfigurationFiles,
            155 => PropertyIdentifier::DatabaseRevision,
            156 => PropertyIdentifier::DirectReading,
            157 => PropertyIdentifier::LastRestoreTime,
            158 => PropertyIdentifier::MaintenanceRequired,
            159 => PropertyIdentifier::MemberOf,
            160 => PropertyIdentifier::Mode,
            161 => PropertyIdentifier::OperationExpected,
            162 => PropertyIdentifier::Setting,
            163 => PropertyIdentifier::Silenced,
            164 => PropertyIdentifier::TrackingValue,
            165 => PropertyIdentifier::ZoneMembers,
            166 => PropertyIdentifier::LifeSafetyAlarmValues,
            167 => PropertyIdentifier::MaxSegmentsAccepted,
            168 => PropertyIdentifier::ProfileLocation,
            169 => PropertyIdentifier::AutoSlaveDiscovery,
            170 => PropertyIdentifier::ManualSlaveAddressBinding,
            171 => PropertyIdentifier::SlaveAddressBinding,
            172 => PropertyIdentifier::SlaveProxyEnable,
            173 => PropertyIdentifier::LastNotifyRecord,
            174 => PropertyIdentifier::ScheduleDefault,
            175 => PropertyIdentifier::AcceptedModes,
            176 => PropertyIdentifier::AdjustValue,
            177 => PropertyIdentifier::Count,
            178 => PropertyIdentifier::CountBeforeChange,
            179 => PropertyIdentifier::CountChangeTime,
            180 => PropertyIdentifier::CovPeriod,
            181 => PropertyIdentifier::InputReference,
            182 => PropertyIdentifier::LimitMonitoringInterval,
            183 => PropertyIdentifier::LoggingObject,
            184 => PropertyIdentifier::LoggingRecord,
            185 => PropertyIdentifier::Prescale,
            186 => PropertyIdentifier::PulseRate,
            187 => PropertyIdentifier::Scale,
            188 => PropertyIdentifier::ScaleFactor,
            189 => PropertyIdentifier::UpdateTime,
            190 => PropertyIdentifier::ValueBeforeChange,
            191 => PropertyIdentifier::ValueSet,
            192 => PropertyIdentifier::ValueChangeTime,
            193 => PropertyIdentifier::AlignIntervals,
            195 => PropertyIdentifier::IntervalOffset,
            196 => PropertyIdentifier::LastRestartReason,
            197 => PropertyIdentifier::LoggingType,
            202 => PropertyIdentifier::RestartNotificationRecipients,
            203 => PropertyIdentifier::TimeOfDeviceRestart,
            204 => PropertyIdentifier::TimeSynchronizationInterval,
            205 => PropertyIdentifier::Trigger,
            206 => PropertyIdentifier::UtcTimeSynchronizationRecipients,
            207 => PropertyIdentifier::NodeSubtype,
            208 => PropertyIdentifier::NodeType,
            209 => PropertyIdentifier::StructuredObjectList,
            210 => PropertyIdentifier::SubordinateAnnotations,
            211 => PropertyIdentifier::SubordinateList,
            212 => PropertyIdentifier::ActualShedLevel,
            213 => PropertyIdentifier::DutyWindow,
            214 => PropertyIdentifier::ExpectedShedLevel,
            215 => PropertyIdentifier::FullDutyBaseline,
            218 => PropertyIdentifier::RequestedShedLevel,
            219 => PropertyIdentifier::ShedDuration,
            220 => PropertyIdentifier::ShedLevelDescriptions,
            221 => PropertyIdentifier::ShedLevels,
            222 => PropertyIdentifier::StateDescription,
            227 => PropertyIdentifier::DoorAlarmState,
            228 => PropertyIdentifier::DoorExtendedPulseTime,
            229 => PropertyIdentifier::DoorMembers,
            230 => PropertyIdentifier::DoorOpenTooLongTime,
            231 => PropertyIdentifier::DoorPulseTime,
            232 => PropertyIdentifier::DoorStatus,
            233 => PropertyIdentifier::DoorUnlockDelayTime,
            234 => PropertyIdentifier::LockStatus,
            235 => PropertyIdentifier::MaskedAlarmValues,
            236 => PropertyIdentifier::SecuredAccess,
            244 => PropertyIdentifier::AbsenteeLimit,
            245 => PropertyIdentifier::AccessAlarmEvents,
            246 => PropertyIdentifier::AccessDoors,
            247 => PropertyIdentifier::AccessEvent,
            248 => PropertyIdentifier::AccessEventAuthenticationFactor,
            249 => PropertyIdentifier::AccessEventCredential,
            250 => PropertyIdentifier::AccessEventTime,
            251 => PropertyIdentifier::AccessTransactionEvents,
            252 => PropertyIdentifier::Accompaniment,
            253 => PropertyIdentifier::AccompanimentTime,
            254 => PropertyIdentifier::ActivationTime,
            255 => PropertyIdentifier::ActiveAuthenticationPolicy,
            256 => PropertyIdentifier::AssignedAccessRights,
            257 => PropertyIdentifier::AuthenticationFactors,
            258 => PropertyIdentifier::AuthenticationPolicyList,
            259 => PropertyIdentifier::AuthenticationPolicyNames,
            260 => PropertyIdentifier::AuthenticationStatus,
            261 => PropertyIdentifier::AuthorizationMode,
            262 => PropertyIdentifier::BelongsTo,
            263 => PropertyIdentifier::CredentialDisable,
            264 => PropertyIdentifier::CredentialStatus,
            265 => PropertyIdentifier::Credentials,
            266 => PropertyIdentifier::CredentialsInZone,
            267 => PropertyIdentifier::DaysRemaining,
            268 => PropertyIdentifier::EntryPoints,
            269 => PropertyIdentifier::ExitPoints,
            270 => PropertyIdentifier::ExpiryTime,
            271 => PropertyIdentifier::ExtendedTimeEnable,
            272 => PropertyIdentifier::FailedAttemptEvents,
            273 => PropertyIdentifier::FailedAttempts,
            274 => PropertyIdentifier::FailedAttemptsTime,
            275 => PropertyIdentifier::LastAccessEvent,
            276 => PropertyIdentifier::LastAccessPoint,
            277 => PropertyIdentifier::LastCredentialAdded,
            278 => PropertyIdentifier::LastCredentialAddedTime,
            279 => PropertyIdentifier::LastCredentialRemoved,
            280 => PropertyIdentifier::LastCredentialRemovedTime,
            281 => PropertyIdentifier::LastUseTime,
            282 => PropertyIdentifier::Lockout,
            283 => PropertyIdentifier::LockoutRelinquishTime,
            284 => PropertyIdentifier::MasterExemption,
            285 => PropertyIdentifier::MaxFailedAttempts,
            286 => PropertyIdentifier::Members,
            287 => PropertyIdentifier::MemberOf2,
            288 => PropertyIdentifier::NegativeAccessRules,
            289 => PropertyIdentifier::NumberOfAuthenticationPolicies,
            290 => PropertyIdentifier::OccupancyCount,
            291 => PropertyIdentifier::OccupancyCountAdjust,
            292 => PropertyIdentifier::OccupancyCountEnable,
            293 => PropertyIdentifier::OccupancyExemption,
            294 => PropertyIdentifier::OccupancyLowerLimit,
            295 => PropertyIdentifier::OccupancyLowerLimitEnforced,
            296 => PropertyIdentifier::OccupancyState,
            297 => PropertyIdentifier::OccupancyUpperLimit,
            298 => PropertyIdentifier::OccupancyUpperLimitEnforced,
            299 => PropertyIdentifier::PassbackExemption,
            300 => PropertyIdentifier::PassbackMode,
            301 => PropertyIdentifier::PassbackTimeout,
            302 => PropertyIdentifier::PositiveAccessRules,
            303 => PropertyIdentifier::ReasonForDisable,
            304 => PropertyIdentifier::SupportedFormats,
            305 => PropertyIdentifier::SupportedFormatClasses,
            306 => PropertyIdentifier::ThreatAuthority,
            307 => PropertyIdentifier::ThreatLevel,
            308 => PropertyIdentifier::TraceFlag,
            309 => PropertyIdentifier::TransactionNotificationClass,
            310 => PropertyIdentifier::UserExternalIdentifier,
            311 => PropertyIdentifier::UserInformationReference,
            317 => PropertyIdentifier::UserName,
            318 => PropertyIdentifier::UserType,
            319 => PropertyIdentifier::UsesRemaining,
            320 => PropertyIdentifier::ZoneFrom,
            321 => PropertyIdentifier::ZoneTo,
            322 => PropertyIdentifier::AccessEventTag,
            323 => PropertyIdentifier::GlobalIdentifier,
            326 => PropertyIdentifier::VerificationTime,
            327 => PropertyIdentifier::BaseDeviceSecurityPolicy,
            328 => PropertyIdentifier::DistributionKeyRevision,
            329 => PropertyIdentifier::DoNotHide,
            330 => PropertyIdentifier::KeySets,
            331 => PropertyIdentifier::LastKeyServer,
            332 => PropertyIdentifier::NetworkAccessSecurityPolicies,
            333 => PropertyIdentifier::PacketReorderTime,
            334 => PropertyIdentifier::SecurityPduTimeout,
            335 => PropertyIdentifier::SecurityTimeWindow,
            336 => PropertyIdentifier::SupportedSecurityAlgorithm,
            337 => PropertyIdentifier::UpdateKeySetTimeout,
            338 => PropertyIdentifier::BackupAndRestoreState,
            339 => PropertyIdentifier::BackupPreparationTime,
            340 => PropertyIdentifier::RestoreCompletionTime,
            341 => PropertyIdentifier::RestorePreparationTime,
            342 => PropertyIdentifier::BitMask,
            343 => PropertyIdentifier::BitText,
            344 => PropertyIdentifier::IsUtc,
            345 => PropertyIdentifier::GroupMembers,
            346 => PropertyIdentifier::GroupMemberNames,
            347 => PropertyIdentifier::MemberStatusFlags,
            348 => PropertyIdentifier::RequestedUpdateInterval,
            349 => PropertyIdentifier::Resolution2,
            350 => PropertyIdentifier::CovuPeriod,
            351 => PropertyIdentifier::CovuRecipients,
            352 => PropertyIdentifier::EventMessageTexts,
            353 => PropertyIdentifier::EventMessageTextsConfig,
            354 => PropertyIdentifier::EventDetectionEnable,
            355 => PropertyIdentifier::EventAlgorithmInhibit,
            356 => PropertyIdentifier::EventAlgorithmInhibitRef,
            357 => PropertyIdentifier::TimeDelayNormal,
            358 => PropertyIdentifier::ReliabilityEvaluationInhibit,
            359 => PropertyIdentifier::FaultParameters,
            360 => PropertyIdentifier::FaultType,
            361 => PropertyIdentifier::LocalForwardingOnly,
            362 => PropertyIdentifier::ProcessIdentifierFilter,
            363 => PropertyIdentifier::SubscribedRecipients,
            364 => PropertyIdentifier::PortFilter,
            365 => PropertyIdentifier::AuthorizationExemptions,
            366 => PropertyIdentifier::AllowGroupDelayInhibit,
            367 => PropertyIdentifier::ChannelNumber,
            368 => PropertyIdentifier::ControlGroups,
            369 => PropertyIdentifier::ExecutionDelay,
            370 => PropertyIdentifier::LastPriority,
            371 => PropertyIdentifier::WriteStatus,
            372 => PropertyIdentifier::PropertyList,
            373 => PropertyIdentifier::SerialNumber,
            374 => PropertyIdentifier::BlinkWarnEnable,
            375 => PropertyIdentifier::DefaultFadeTime,
            376 => PropertyIdentifier::DefaultRampRate,
            377 => PropertyIdentifier::DefaultStepIncrement,
            378 => PropertyIdentifier::EgressActive,
            379 => PropertyIdentifier::EgressTime,
            380 => PropertyIdentifier::InProgress,
            381 => PropertyIdentifier::InstantianeousPower,
            382 => PropertyIdentifier::LightingCommand,
            383 => PropertyIdentifier::LightingCommandDefaultPriority,
            384 => PropertyIdentifier::MaxActualValue,
            385 => PropertyIdentifier::MinActualValue,
            386 => PropertyIdentifier::Power,
            387 => PropertyIdentifier::Transition,
            v => PropertyIdentifier::Unknown(v),
        }
    }
}

impl From<PropertyIdentifier> for u32 {
    fn from(p: PropertyIdentifier) -> u32 {
        match p {
            PropertyIdentifier::AckedTransitions => 0,
            PropertyIdentifier::AckRequired => 1,
            PropertyIdentifier::Action => 2,
            PropertyIdentifier::ActionText => 3,
            PropertyIdentifier::ActiveText => 4,
            PropertyIdentifier::ActiveVtSessions => 5,
            PropertyIdentifier::AlarmValue => 6,
            PropertyIdentifier::AlarmValues => 7,
            PropertyIdentifier::All => 8,
            PropertyIdentifier::AllWritesSuccessful => 9,
            PropertyIdentifier::ApduSegmentTimeout => 10,
            PropertyIdentifier::ApduTimeout => 11,
            PropertyIdentifier::ApplicationSoftwareVersion => 12,
            PropertyIdentifier::Archive => 13,
            PropertyIdentifier::Bias => 14,
            PropertyIdentifier::ChangeOfStateCount => 15,
            PropertyIdentifier::ChangeOfStateTime => 16,
            PropertyIdentifier::NotificationClass => 17,
            PropertyIdentifier::Deadband => 19,
            PropertyIdentifier::DerivativeConstant => 20,
            PropertyIdentifier::DerivativeConstantUnits => 21,
            PropertyIdentifier::Description => 28,
            PropertyIdentifier::DescriptionOfHalt => 29,
            PropertyIdentifier::DeviceAddressBinding => 30,
            PropertyIdentifier::DeviceType => 31,
            PropertyIdentifier::EffectivePeriod => 32,
            PropertyIdentifier::ElapsedActiveTime => 33,
            PropertyIdentifier::ErrorLimit => 34,
            PropertyIdentifier::EventEnable => 35,
            PropertyIdentifier::EventState => 36,
            PropertyIdentifier::EventType => 37,
            PropertyIdentifier::ExceptionSchedule => 38,
            PropertyIdentifier::FaultValues => 39,
            PropertyIdentifier::FeedbackValue => 40,
            PropertyIdentifier::FileAccessMethod => 41,
            PropertyIdentifier::FileSize => 42,
            PropertyIdentifier::FileType => 43,
            PropertyIdentifier::FirmwareRevision => 44,
            PropertyIdentifier::HighLimit => 45,
            PropertyIdentifier::InactiveText => 46,
            PropertyIdentifier::InProcess => 47,
            PropertyIdentifier::InstanceOf => 48,
            PropertyIdentifier::IntegralConstant => 49,
            PropertyIdentifier::IntegralConstantUnits => 50,
            PropertyIdentifier::LimitEnable => 52,
            PropertyIdentifier::ListOfGroupMembers => 53,
            PropertyIdentifier::ListOfObjectPropertyReferences => 54,
            PropertyIdentifier::ListOfSessionKeys => 55,
            PropertyIdentifier::LocalDate => 56,
            PropertyIdentifier::LocalTime => 57,
            PropertyIdentifier::Location => 58,
            PropertyIdentifier::LowLimit => 59,
            PropertyIdentifier::ManipulatedVariableReference => 60,
            PropertyIdentifier::MaximumOutput => 61,
            PropertyIdentifier::MaxApduLengthAccepted => 62,
            PropertyIdentifier::MaxInfoFrames => 63,
            PropertyIdentifier::MaxMaster => 64,
            PropertyIdentifier::MaxPresValue => 65,
            PropertyIdentifier::MinimumOffTime => 66,
            PropertyIdentifier::MinimumOnTime => 67,
            PropertyIdentifier::MinimumOutput => 68,
            PropertyIdentifier::MinPresValue => 69,
            PropertyIdentifier::ModelName => 70,
            PropertyIdentifier::ModificationDate => 71,
            PropertyIdentifier::NotifyType => 72,
            PropertyIdentifier::NumberOfApduRetries => 73,
            PropertyIdentifier::NumberOfStates => 74,
            PropertyIdentifier::ObjectIdentifier => 75,
            PropertyIdentifier::ObjectList => 76,
            PropertyIdentifier::ObjectName => 77,
            PropertyIdentifier::ObjectPropertyReference => 78,
            PropertyIdentifier::ObjectType => 79,
            PropertyIdentifier::Optional => 80,
            PropertyIdentifier::OutOfService => 81,
            PropertyIdentifier::OutputUnits => 82,
            PropertyIdentifier::EventParameters => 83,
            PropertyIdentifier::Polarity => 84,
            PropertyIdentifier::PresentValue => 85,
            PropertyIdentifier::Priority => 86,
            PropertyIdentifier::PriorityArray => 87,
            PropertyIdentifier::PriorityForWriting => 88,
            PropertyIdentifier::ProcessIdentifier => 89,
            PropertyIdentifier::ProgramChange => 90,
            PropertyIdentifier::ProgramLocation => 91,
            PropertyIdentifier::ProgramState => 92,
            PropertyIdentifier::ProportionalConstant => 93,
            PropertyIdentifier::ProportionalConstantUnits => 94,
            PropertyIdentifier::ProtocolObjectTypesSupported => 96,
            PropertyIdentifier::ProtocolServicesSupported => 97,
            PropertyIdentifier::ProtocolVersion => 98,
            PropertyIdentifier::ReadOnly => 99,
            PropertyIdentifier::ReasonForHalt => 100,
            PropertyIdentifier::Recipient => 101,
            PropertyIdentifier::RecipientList => 102,
            PropertyIdentifier::Reliability => 103,
            PropertyIdentifier::RelinquishDefault => 104,
            PropertyIdentifier::Required => 105,
            PropertyIdentifier::Resolution => 106,
            PropertyIdentifier::SegmentationSupported => 107,
            PropertyIdentifier::Setpoint => 108,
            PropertyIdentifier::SetpointReference => 109,
            PropertyIdentifier::StateText => 110,
            PropertyIdentifier::StatusFlags => 111,
            PropertyIdentifier::SystemStatus => 112,
            PropertyIdentifier::TimeDelay => 113,
            PropertyIdentifier::TimeOfActiveTimeReset => 114,
            PropertyIdentifier::TimeOfStateCountReset => 115,
            PropertyIdentifier::TimeSynchronizationRecipients => 116,
            PropertyIdentifier::Units => 117,
            PropertyIdentifier::UpdateInterval => 118,
            PropertyIdentifier::UtcOffset => 119,
            PropertyIdentifier::VendorIdentifier => 120,
            PropertyIdentifier::VendorName => 121,
            PropertyIdentifier::VtClassesSupported => 122,
            PropertyIdentifier::WeeklySchedule => 123,
            PropertyIdentifier::AttemptedSamples => 124,
            PropertyIdentifier::AverageValue => 125,
            PropertyIdentifier::BufferSize => 126,
            PropertyIdentifier::ClientCovIncrement => 127,
            PropertyIdentifier::CovResubscriptionInterval => 128,
            PropertyIdentifier::CurrentNotifyTime => 129,
            PropertyIdentifier::EventTimeStamps => 130,
            PropertyIdentifier::LogBuffer => 131,
            PropertyIdentifier::LogDeviceObjectProperty => 132,
            PropertyIdentifier::Enable => 133,
            PropertyIdentifier::LogInterval => 134,
            PropertyIdentifier::MaximumValue => 135,
            PropertyIdentifier::MinimumValue => 136,
            PropertyIdentifier::NotificationThreshold => 137,
            PropertyIdentifier::PreviousNotifyTime => 138,
            PropertyIdentifier::ProfileName => 139,
            PropertyIdentifier::RecordCount => 140,
            PropertyIdentifier::RecordsSinceNotification => 141,
            PropertyIdentifier::StartTime => 142,
            PropertyIdentifier::StopTime => 143,
            PropertyIdentifier::StopWhenFull => 144,
            PropertyIdentifier::TotalRecordCount => 145,
            PropertyIdentifier::ValidSamples => 146,
            PropertyIdentifier::WindowInterval => 147,
            PropertyIdentifier::WindowSamples => 148,
            PropertyIdentifier::MaximumValueTimestamp => 149,
            PropertyIdentifier::MinimumValueTimestamp => 150,
            PropertyIdentifier::Variance => 151,
            PropertyIdentifier::ActiveCovSubscriptions => 152,
            PropertyIdentifier::BackupFailureTimeout => 153,
            PropertyIdentifier::ConfigurationFiles => 154,
            PropertyIdentifier::DatabaseRevision => 155,
            PropertyIdentifier::DirectReading => 156,
            PropertyIdentifier::LastRestoreTime => 157,
            PropertyIdentifier::MaintenanceRequired => 158,
            PropertyIdentifier::MemberOf => 159,
            PropertyIdentifier::Mode => 160,
            PropertyIdentifier::OperationExpected => 161,
            PropertyIdentifier::Setting => 162,
            PropertyIdentifier::Silenced => 163,
            PropertyIdentifier::TrackingValue => 164,
            PropertyIdentifier::ZoneMembers => 165,
            PropertyIdentifier::LifeSafetyAlarmValues => 166,
            PropertyIdentifier::MaxSegmentsAccepted => 167,
            PropertyIdentifier::ProfileLocation => 168,
            PropertyIdentifier::AutoSlaveDiscovery => 169,
            PropertyIdentifier::ManualSlaveAddressBinding => 170,
            PropertyIdentifier::SlaveAddressBinding => 171,
            PropertyIdentifier::SlaveProxyEnable => 172,
            PropertyIdentifier::LastNotifyRecord => 173,
            PropertyIdentifier::ScheduleDefault => 174,
            PropertyIdentifier::AcceptedModes => 175,
            PropertyIdentifier::AdjustValue => 176,
            PropertyIdentifier::Count => 177,
            PropertyIdentifier::CountBeforeChange => 178,
            PropertyIdentifier::CountChangeTime => 179,
            PropertyIdentifier::CovPeriod => 180,
            PropertyIdentifier::InputReference => 181,
            PropertyIdentifier::LimitMonitoringInterval => 182,
            PropertyIdentifier::LoggingObject => 183,
            PropertyIdentifier::LoggingRecord => 184,
            PropertyIdentifier::Prescale => 185,
            PropertyIdentifier::PulseRate => 186,
            PropertyIdentifier::Scale => 187,
            PropertyIdentifier::ScaleFactor => 188,
            PropertyIdentifier::UpdateTime => 189,
            PropertyIdentifier::ValueBeforeChange => 190,
            PropertyIdentifier::ValueSet => 191,
            PropertyIdentifier::ValueChangeTime => 192,
            PropertyIdentifier::AlignIntervals => 193,
            PropertyIdentifier::IntervalOffset => 195,
            PropertyIdentifier::LastRestartReason => 196,
            PropertyIdentifier::LoggingType => 197,
            PropertyIdentifier::RestartNotificationRecipients => 202,
            PropertyIdentifier::TimeOfDeviceRestart => 203,
            PropertyIdentifier::TimeSynchronizationInterval => 204,
            PropertyIdentifier::Trigger => 205,
            PropertyIdentifier::UtcTimeSynchronizationRecipients => 206,
            PropertyIdentifier::NodeSubtype => 207,
            PropertyIdentifier::NodeType => 208,
            PropertyIdentifier::StructuredObjectList => 209,
            PropertyIdentifier::SubordinateAnnotations => 210,
            PropertyIdentifier::SubordinateList => 211,
            PropertyIdentifier::ActualShedLevel => 212,
            PropertyIdentifier::DutyWindow => 213,
            PropertyIdentifier::ExpectedShedLevel => 214,
            PropertyIdentifier::FullDutyBaseline => 215,
            PropertyIdentifier::RequestedShedLevel => 218,
            PropertyIdentifier::ShedDuration => 219,
            PropertyIdentifier::ShedLevelDescriptions => 220,
            PropertyIdentifier::ShedLevels => 221,
            PropertyIdentifier::StateDescription => 222,
            PropertyIdentifier::DoorAlarmState => 227,
            PropertyIdentifier::DoorExtendedPulseTime => 228,
            PropertyIdentifier::DoorMembers => 229,
            PropertyIdentifier::DoorOpenTooLongTime => 230,
            PropertyIdentifier::DoorPulseTime => 231,
            PropertyIdentifier::DoorStatus => 232,
            PropertyIdentifier::DoorUnlockDelayTime => 233,
            PropertyIdentifier::LockStatus => 234,
            PropertyIdentifier::MaskedAlarmValues => 235,
            PropertyIdentifier::SecuredAccess => 236,
            PropertyIdentifier::AbsenteeLimit => 244,
            PropertyIdentifier::AccessAlarmEvents => 245,
            PropertyIdentifier::AccessDoors => 246,
            PropertyIdentifier::AccessEvent => 247,
            PropertyIdentifier::AccessEventAuthenticationFactor => 248,
            PropertyIdentifier::AccessEventCredential => 249,
            PropertyIdentifier::AccessEventTime => 250,
            PropertyIdentifier::AccessTransactionEvents => 251,
            PropertyIdentifier::Accompaniment => 252,
            PropertyIdentifier::AccompanimentTime => 253,
            PropertyIdentifier::ActivationTime => 254,
            PropertyIdentifier::ActiveAuthenticationPolicy => 255,
            PropertyIdentifier::AssignedAccessRights => 256,
            PropertyIdentifier::AuthenticationFactors => 257,
            PropertyIdentifier::AuthenticationPolicyList => 258,
            PropertyIdentifier::AuthenticationPolicyNames => 259,
            PropertyIdentifier::AuthenticationStatus => 260,
            PropertyIdentifier::AuthorizationMode => 261,
            PropertyIdentifier::BelongsTo => 262,
            PropertyIdentifier::CredentialDisable => 263,
            PropertyIdentifier::CredentialStatus => 264,
            PropertyIdentifier::Credentials => 265,
            PropertyIdentifier::CredentialsInZone => 266,
            PropertyIdentifier::DaysRemaining => 267,
            PropertyIdentifier::EntryPoints => 268,
            PropertyIdentifier::ExitPoints => 269,
            PropertyIdentifier::ExpiryTime => 270,
            PropertyIdentifier::ExtendedTimeEnable => 271,
            PropertyIdentifier::FailedAttemptEvents => 272,
            PropertyIdentifier::FailedAttempts => 273,
            PropertyIdentifier::FailedAttemptsTime => 274,
            PropertyIdentifier::LastAccessEvent => 275,
            PropertyIdentifier::LastAccessPoint => 276,
            PropertyIdentifier::LastCredentialAdded => 277,
            PropertyIdentifier::LastCredentialAddedTime => 278,
            PropertyIdentifier::LastCredentialRemoved => 279,
            PropertyIdentifier::LastCredentialRemovedTime => 280,
            PropertyIdentifier::LastUseTime => 281,
            PropertyIdentifier::Lockout => 282,
            PropertyIdentifier::LockoutRelinquishTime => 283,
            PropertyIdentifier::MasterExemption => 284,
            PropertyIdentifier::MaxFailedAttempts => 285,
            PropertyIdentifier::Members => 286,
            PropertyIdentifier::MemberOf2 => 287,
            PropertyIdentifier::NegativeAccessRules => 288,
            PropertyIdentifier::NumberOfAuthenticationPolicies => 289,
            PropertyIdentifier::OccupancyCount => 290,
            PropertyIdentifier::OccupancyCountAdjust => 291,
            PropertyIdentifier::OccupancyCountEnable => 292,
            PropertyIdentifier::OccupancyExemption => 293,
            PropertyIdentifier::OccupancyLowerLimit => 294,
            PropertyIdentifier::OccupancyLowerLimitEnforced => 295,
            PropertyIdentifier::OccupancyState => 296,
            PropertyIdentifier::OccupancyUpperLimit => 297,
            PropertyIdentifier::OccupancyUpperLimitEnforced => 298,
            PropertyIdentifier::PassbackExemption => 299,
            PropertyIdentifier::PassbackMode => 300,
            PropertyIdentifier::PassbackTimeout => 301,
            PropertyIdentifier::PositiveAccessRules => 302,
            PropertyIdentifier::ReasonForDisable => 303,
            PropertyIdentifier::SupportedFormats => 304,
            PropertyIdentifier::SupportedFormatClasses => 305,
            PropertyIdentifier::ThreatAuthority => 306,
            PropertyIdentifier::ThreatLevel => 307,
            PropertyIdentifier::TraceFlag => 308,
            PropertyIdentifier::TransactionNotificationClass => 309,
            PropertyIdentifier::UserExternalIdentifier => 310,
            PropertyIdentifier::UserInformationReference => 311,
            PropertyIdentifier::UserName => 317,
            PropertyIdentifier::UserType => 318,
            PropertyIdentifier::UsesRemaining => 319,
            PropertyIdentifier::ZoneFrom => 320,
            PropertyIdentifier::ZoneTo => 321,
            PropertyIdentifier::AccessEventTag => 322,
            PropertyIdentifier::GlobalIdentifier => 323,
            PropertyIdentifier::VerificationTime => 326,
            PropertyIdentifier::BaseDeviceSecurityPolicy => 327,
            PropertyIdentifier::DistributionKeyRevision => 328,
            PropertyIdentifier::DoNotHide => 329,
            PropertyIdentifier::KeySets => 330,
            PropertyIdentifier::LastKeyServer => 331,
            PropertyIdentifier::NetworkAccessSecurityPolicies => 332,
            PropertyIdentifier::PacketReorderTime => 333,
            PropertyIdentifier::SecurityPduTimeout => 334,
            PropertyIdentifier::SecurityTimeWindow => 335,
            PropertyIdentifier::SupportedSecurityAlgorithm => 336,
            PropertyIdentifier::UpdateKeySetTimeout => 337,
            PropertyIdentifier::BackupAndRestoreState => 338,
            PropertyIdentifier::BackupPreparationTime => 339,
            PropertyIdentifier::RestoreCompletionTime => 340,
            PropertyIdentifier::RestorePreparationTime => 341,
            PropertyIdentifier::BitMask => 342,
            PropertyIdentifier::BitText => 343,
            PropertyIdentifier::IsUtc => 344,
            PropertyIdentifier::GroupMembers => 345,
            PropertyIdentifier::GroupMemberNames => 346,
            PropertyIdentifier::MemberStatusFlags => 347,
            PropertyIdentifier::RequestedUpdateInterval => 348,
            PropertyIdentifier::Resolution2 => 349,
            PropertyIdentifier::CovuPeriod => 350,
            PropertyIdentifier::CovuRecipients => 351,
            PropertyIdentifier::EventMessageTexts => 352,
            PropertyIdentifier::EventMessageTextsConfig => 353,
            PropertyIdentifier::EventDetectionEnable => 354,
            PropertyIdentifier::EventAlgorithmInhibit => 355,
            PropertyIdentifier::EventAlgorithmInhibitRef => 356,
            PropertyIdentifier::TimeDelayNormal => 357,
            PropertyIdentifier::ReliabilityEvaluationInhibit => 358,
            PropertyIdentifier::FaultParameters => 359,
            PropertyIdentifier::FaultType => 360,
            PropertyIdentifier::LocalForwardingOnly => 361,
            PropertyIdentifier::ProcessIdentifierFilter => 362,
            PropertyIdentifier::SubscribedRecipients => 363,
            PropertyIdentifier::PortFilter => 364,
            PropertyIdentifier::AuthorizationExemptions => 365,
            PropertyIdentifier::AllowGroupDelayInhibit => 366,
            PropertyIdentifier::ChannelNumber => 367,
            PropertyIdentifier::ControlGroups => 368,
            PropertyIdentifier::ExecutionDelay => 369,
            PropertyIdentifier::LastPriority => 370,
            PropertyIdentifier::WriteStatus => 371,
            PropertyIdentifier::PropertyList => 372,
            PropertyIdentifier::SerialNumber => 373,
            PropertyIdentifier::BlinkWarnEnable => 374,
            PropertyIdentifier::DefaultFadeTime => 375,
            PropertyIdentifier::DefaultRampRate => 376,
            PropertyIdentifier::DefaultStepIncrement => 377,
            PropertyIdentifier::EgressActive => 378,
            PropertyIdentifier::EgressTime => 379,
            PropertyIdentifier::InProgress => 380,
            PropertyIdentifier::InstantianeousPower => 381,
            PropertyIdentifier::LightingCommand => 382,
            PropertyIdentifier::LightingCommandDefaultPriority => 383,
            PropertyIdentifier::MaxActualValue => 384,
            PropertyIdentifier::MinActualValue => 385,
            PropertyIdentifier::Power => 386,
            PropertyIdentifier::Transition => 387,
            PropertyIdentifier::Unknown(v) => v,
        }
    }
}

impl fmt::Display for PropertyIdentifier {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PropertyIdentifier::AckedTransitions => write!(f, "acked-transitions"),
            PropertyIdentifier::AckRequired => write!(f, "ack-required"),
            PropertyIdentifier::Action => write!(f, "action"),
            PropertyIdentifier::ActionText => write!(f, "action-text"),
            PropertyIdentifier::ActiveText => write!(f, "active-text"),
            PropertyIdentifier::ActiveVtSessions => write!(f, "active-vt-sessions"),
            PropertyIdentifier::AlarmValue => write!(f, "alarm-value"),
            PropertyIdentifier::AlarmValues => write!(f, "alarm-values"),
            PropertyIdentifier::All => write!(f, "all"),
            PropertyIdentifier::AllWritesSuccessful => write!(f, "all-writes-successful"),
            PropertyIdentifier::ApduSegmentTimeout => write!(f, "apdu-segment-timeout"),
            PropertyIdentifier::ApduTimeout => write!(f, "apdu-timeout"),
            PropertyIdentifier::ApplicationSoftwareVersion => {
                write!(f, "application-software-version")
            }
            PropertyIdentifier::Archive => write!(f, "archive"),
            PropertyIdentifier::Bias => write!(f, "bias"),
            PropertyIdentifier::ChangeOfStateCount => write!(f, "change-of-state-count"),
            PropertyIdentifier::ChangeOfStateTime => write!(f, "change-of-state-time"),
            PropertyIdentifier::NotificationClass => write!(f, "notification-class"),
            PropertyIdentifier::Deadband => write!(f, "deadband"),
            PropertyIdentifier::DerivativeConstant => write!(f, "derivative-constant"),
            PropertyIdentifier::DerivativeConstantUnits => write!(f, "derivative-constant-units"),
            PropertyIdentifier::Description => write!(f, "description"),
            PropertyIdentifier::DescriptionOfHalt => write!(f, "description-of-halt"),
            PropertyIdentifier::DeviceAddressBinding => write!(f, "device-address-binding"),
            PropertyIdentifier::DeviceType => write!(f, "device-type"),
            PropertyIdentifier::EffectivePeriod => write!(f, "effective-period"),
            PropertyIdentifier::ElapsedActiveTime => write!(f, "elapsed-active-time"),
            PropertyIdentifier::ErrorLimit => write!(f, "error-limit"),
            PropertyIdentifier::EventEnable => write!(f, "event-enable"),
            PropertyIdentifier::EventState => write!(f, "event-state"),
            PropertyIdentifier::EventType => write!(f, "event-type"),
            PropertyIdentifier::ExceptionSchedule => write!(f, "exception-schedule"),
            PropertyIdentifier::FaultValues => write!(f, "fault-values"),
            PropertyIdentifier::FeedbackValue => write!(f, "feedback-value"),
            PropertyIdentifier::FileAccessMethod => write!(f, "file-access-method"),
            PropertyIdentifier::FileSize => write!(f, "file-size"),
            PropertyIdentifier::FileType => write!(f, "file-type"),
            PropertyIdentifier::FirmwareRevision => write!(f, "firmware-revision"),
            PropertyIdentifier::HighLimit => write!(f, "high-limit"),
            PropertyIdentifier::InactiveText => write!(f, "inactive-text"),
            PropertyIdentifier::InProcess => write!(f, "in-process"),
            PropertyIdentifier::InstanceOf => write!(f, "instance-of"),
            PropertyIdentifier::IntegralConstant => write!(f, "integral-constant"),
            PropertyIdentifier::IntegralConstantUnits => write!(f, "integral-constant-units"),
            PropertyIdentifier::LimitEnable => write!(f, "limit-enable"),
            PropertyIdentifier::ListOfGroupMembers => write!(f, "list-of-group-members"),
            PropertyIdentifier::ListOfObjectPropertyReferences => {
                write!(f, "list-of-object-property-references")
            }
            PropertyIdentifier::ListOfSessionKeys => write!(f, "list-of-session-keys"),
            PropertyIdentifier::LocalDate => write!(f, "local-date"),
            PropertyIdentifier::LocalTime => write!(f, "local-time"),
            PropertyIdentifier::Location => write!(f, "location"),
            PropertyIdentifier::LowLimit => write!(f, "low-limit"),
            PropertyIdentifier::ManipulatedVariableReference => {
                write!(f, "manipulated-variable-reference")
            }
            PropertyIdentifier::MaximumOutput => write!(f, "maximum-output"),
            PropertyIdentifier::MaxApduLengthAccepted => write!(f, "max-apdu-length-accepted"),
            PropertyIdentifier::MaxInfoFrames => write!(f, "max-info-frames"),
            PropertyIdentifier::MaxMaster => write!(f, "max-master"),
            PropertyIdentifier::MaxPresValue => write!(f, "max-pres-value"),
            PropertyIdentifier::MinimumOffTime => write!(f, "minimum-off-time"),
            PropertyIdentifier::MinimumOnTime => write!(f, "minimum-on-time"),
            PropertyIdentifier::MinimumOutput => write!(f, "minimum-output"),
            PropertyIdentifier::MinPresValue => write!(f, "min-pres-value"),
            PropertyIdentifier::ModelName => write!(f, "model-name"),
            PropertyIdentifier::ModificationDate => write!(f, "modification-date"),
            PropertyIdentifier::NotifyType => write!(f, "notify-type"),
            PropertyIdentifier::NumberOfApduRetries => write!(f, "number-of-apdu-retries"),
            PropertyIdentifier::NumberOfStates => write!(f, "number-of-states"),
            PropertyIdentifier::ObjectIdentifier => write!(f, "object-identifier"),
            PropertyIdentifier::ObjectList => write!(f, "object-list"),
            PropertyIdentifier::ObjectName => write!(f, "object-name"),
            PropertyIdentifier::ObjectPropertyReference => write!(f, "object-property-reference"),
            PropertyIdentifier::ObjectType => write!(f, "object-type"),
            PropertyIdentifier::Optional => write!(f, "optional"),
            PropertyIdentifier::OutOfService => write!(f, "out-of-service"),
            PropertyIdentifier::OutputUnits => write!(f, "output-units"),
            PropertyIdentifier::EventParameters => write!(f, "event-parameters"),
            PropertyIdentifier::Polarity => write!(f, "polarity"),
            PropertyIdentifier::PresentValue => write!(f, "present-value"),
            PropertyIdentifier::Priority => write!(f, "priority"),
            PropertyIdentifier::PriorityArray => write!(f, "priority-array"),
            PropertyIdentifier::PriorityForWriting => write!(f, "priority-for-writing"),
            PropertyIdentifier::ProcessIdentifier => write!(f, "process-identifier"),
            PropertyIdentifier::ProgramChange => write!(f, "program-change"),
            PropertyIdentifier::ProgramLocation => write!(f, "program-location"),
            PropertyIdentifier::ProgramState => write!(f, "program-state"),
            PropertyIdentifier::ProportionalConstant => write!(f, "proportional-constant"),
            PropertyIdentifier::ProportionalConstantUnits => {
                write!(f, "proportional-constant-units")
            }
            PropertyIdentifier::ProtocolObjectTypesSupported => {
                write!(f, "protocol-object-types-supported")
            }
            PropertyIdentifier::ProtocolServicesSupported => {
                write!(f, "protocol-services-supported")
            }
            PropertyIdentifier::ProtocolVersion => write!(f, "protocol-version"),
            PropertyIdentifier::ReadOnly => write!(f, "read-only"),
            PropertyIdentifier::ReasonForHalt => write!(f, "reason-for-halt"),
            PropertyIdentifier::Recipient => write!(f, "recipient"),
            PropertyIdentifier::RecipientList => write!(f, "recipient-list"),
            PropertyIdentifier::Reliability => write!(f, "reliability"),
            PropertyIdentifier::RelinquishDefault => write!(f, "relinquish-default"),
            PropertyIdentifier::Required => write!(f, "required"),
            PropertyIdentifier::Resolution => write!(f, "resolution"),
            PropertyIdentifier::SegmentationSupported => write!(f, "segmentation-supported"),
            PropertyIdentifier::Setpoint => write!(f, "setpoint"),
            PropertyIdentifier::SetpointReference => write!(f, "setpoint-reference"),
            PropertyIdentifier::StateText => write!(f, "state-text"),
            PropertyIdentifier::StatusFlags => write!(f, "status-flags"),
            PropertyIdentifier::SystemStatus => write!(f, "system-status"),
            PropertyIdentifier::TimeDelay => write!(f, "time-delay"),
            PropertyIdentifier::TimeOfActiveTimeReset => write!(f, "time-of-active-time-reset"),
            PropertyIdentifier::TimeOfStateCountReset => write!(f, "time-of-state-count-reset"),
            PropertyIdentifier::TimeSynchronizationRecipients => {
                write!(f, "time-synchronization-recipients")
            }
            PropertyIdentifier::Units => write!(f, "units"),
            PropertyIdentifier::UpdateInterval => write!(f, "update-interval"),
            PropertyIdentifier::UtcOffset => write!(f, "utc-offset"),
            PropertyIdentifier::VendorIdentifier => write!(f, "vendor-identifier"),
            PropertyIdentifier::VendorName => write!(f, "vendor-name"),
            PropertyIdentifier::VtClassesSupported => write!(f, "vt-classes-supported"),
            PropertyIdentifier::WeeklySchedule => write!(f, "weekly-schedule"),
            PropertyIdentifier::AttemptedSamples => write!(f, "attempted-samples"),
            PropertyIdentifier::AverageValue => write!(f, "average-value"),
            PropertyIdentifier::BufferSize => write!(f, "buffer-size"),
            PropertyIdentifier::ClientCovIncrement => write!(f, "client-cov-increment"),
            PropertyIdentifier::CovResubscriptionInterval => {
                write!(f, "cov-resubscription-interval")
            }
            PropertyIdentifier::CurrentNotifyTime => write!(f, "current-notify-time"),
            PropertyIdentifier::EventTimeStamps => write!(f, "event-time-stamps"),
            PropertyIdentifier::LogBuffer => write!(f, "log-buffer"),
            PropertyIdentifier::LogDeviceObjectProperty => write!(f, "log-device-object-property"),
            PropertyIdentifier::Enable => write!(f, "enable"),
            PropertyIdentifier::LogInterval => write!(f, "log-interval"),
            PropertyIdentifier::MaximumValue => write!(f, "maximum-value"),
            PropertyIdentifier::MinimumValue => write!(f, "minimum-value"),
            PropertyIdentifier::NotificationThreshold => write!(f, "notification-threshold"),
            PropertyIdentifier::PreviousNotifyTime => write!(f, "previous-notify-time"),
            PropertyIdentifier::ProfileName => write!(f, "profile-name"),
            PropertyIdentifier::RecordCount => write!(f, "record-count"),
            PropertyIdentifier::RecordsSinceNotification => write!(f, "records-since-notification"),
            PropertyIdentifier::StartTime => write!(f, "start-time"),
            PropertyIdentifier::StopTime => write!(f, "stop-time"),
            PropertyIdentifier::StopWhenFull => write!(f, "stop-when-full"),
            PropertyIdentifier::TotalRecordCount => write!(f, "total-record-count"),
            PropertyIdentifier::ValidSamples => write!(f, "valid-samples"),
            PropertyIdentifier::WindowInterval => write!(f, "window-interval"),
            PropertyIdentifier::WindowSamples => write!(f, "window-samples"),
            PropertyIdentifier::MaximumValueTimestamp => write!(f, "maximum-value-timestamp"),
            PropertyIdentifier::MinimumValueTimestamp => write!(f, "minimum-value-timestamp"),
            PropertyIdentifier::Variance => write!(f, "variance"),
            PropertyIdentifier::ActiveCovSubscriptions => write!(f, "active-cov-subscriptions"),
            PropertyIdentifier::BackupFailureTimeout => write!(f, "backup-failure-timeout"),
            PropertyIdentifier::ConfigurationFiles => write!(f, "configuration-files"),
            PropertyIdentifier::DatabaseRevision => write!(f, "database-revision"),
            PropertyIdentifier::DirectReading => write!(f, "direct-reading"),
            PropertyIdentifier::LastRestoreTime => write!(f, "last-restore-time"),
            PropertyIdentifier::MaintenanceRequired => write!(f, "maintenance-required"),
            PropertyIdentifier::MemberOf => write!(f, "member-of"),
            PropertyIdentifier::Mode => write!(f, "mode"),
            PropertyIdentifier::OperationExpected => write!(f, "operation-expected"),
            PropertyIdentifier::Setting => write!(f, "setting"),
            PropertyIdentifier::Silenced => write!(f, "silenced"),
            PropertyIdentifier::TrackingValue => write!(f, "tracking-value"),
            PropertyIdentifier::ZoneMembers => write!(f, "zone-members"),
            PropertyIdentifier::LifeSafetyAlarmValues => write!(f, "life-safety-alarm-values"),
            PropertyIdentifier::MaxSegmentsAccepted => write!(f, "max-segments-accepted"),
            PropertyIdentifier::ProfileLocation => write!(f, "profile-location"),
            PropertyIdentifier::AutoSlaveDiscovery => write!(f, "auto-slave-discovery"),
            PropertyIdentifier::ManualSlaveAddressBinding => {
                write!(f, "manual-slave-address-binding")
            }
            PropertyIdentifier::SlaveAddressBinding => write!(f, "slave-address-binding"),
            PropertyIdentifier::SlaveProxyEnable => write!(f, "slave-proxy-enable"),
            PropertyIdentifier::LastNotifyRecord => write!(f, "last-notify-record"),
            PropertyIdentifier::ScheduleDefault => write!(f, "schedule-default"),
            PropertyIdentifier::AcceptedModes => write!(f, "accepted-modes"),
            PropertyIdentifier::AdjustValue => write!(f, "adjust-value"),
            PropertyIdentifier::Count => write!(f, "count"),
            PropertyIdentifier::CountBeforeChange => write!(f, "count-before-change"),
            PropertyIdentifier::CountChangeTime => write!(f, "count-change-time"),
            PropertyIdentifier::CovPeriod => write!(f, "cov-period"),
            PropertyIdentifier::InputReference => write!(f, "input-reference"),
            PropertyIdentifier::LimitMonitoringInterval => write!(f, "limit-monitoring-interval"),
            PropertyIdentifier::LoggingObject => write!(f, "logging-object"),
            PropertyIdentifier::LoggingRecord => write!(f, "logging-record"),
            PropertyIdentifier::Prescale => write!(f, "prescale"),
            PropertyIdentifier::PulseRate => write!(f, "pulse-rate"),
            PropertyIdentifier::Scale => write!(f, "scale"),
            PropertyIdentifier::ScaleFactor => write!(f, "scale-factor"),
            PropertyIdentifier::UpdateTime => write!(f, "update-time"),
            PropertyIdentifier::ValueBeforeChange => write!(f, "value-before-change"),
            PropertyIdentifier::ValueSet => write!(f, "value-set"),
            PropertyIdentifier::ValueChangeTime => write!(f, "value-change-time"),
            PropertyIdentifier::AlignIntervals => write!(f, "align-intervals"),
            PropertyIdentifier::IntervalOffset => write!(f, "interval-offset"),
            PropertyIdentifier::LastRestartReason => write!(f, "last-restart-reason"),
            PropertyIdentifier::LoggingType => write!(f, "logging-type"),
            PropertyIdentifier::RestartNotificationRecipients => {
                write!(f, "restart-notification-recipients")
            }
            PropertyIdentifier::TimeOfDeviceRestart => write!(f, "time-of-device-restart"),
            PropertyIdentifier::TimeSynchronizationInterval => {
                write!(f, "time-synchronization-interval")
            }
            PropertyIdentifier::Trigger => write!(f, "trigger"),
            PropertyIdentifier::UtcTimeSynchronizationRecipients => {
                write!(f, "utc-time-synchronization-recipients")
            }
            PropertyIdentifier::NodeSubtype => write!(f, "node-subtype"),
            PropertyIdentifier::NodeType => write!(f, "node-type"),
            PropertyIdentifier::StructuredObjectList => write!(f, "structured-object-list"),
            PropertyIdentifier::SubordinateAnnotations => write!(f, "subordinate-annotations"),
            PropertyIdentifier::SubordinateList => write!(f, "subordinate-list"),
            PropertyIdentifier::ActualShedLevel => write!(f, "actual-shed-level"),
            PropertyIdentifier::DutyWindow => write!(f, "duty-window"),
            PropertyIdentifier::ExpectedShedLevel => write!(f, "expected-shed-level"),
            PropertyIdentifier::FullDutyBaseline => write!(f, "full-duty-baseline"),
            PropertyIdentifier::RequestedShedLevel => write!(f, "requested-shed-level"),
            PropertyIdentifier::ShedDuration => write!(f, "shed-duration"),
            PropertyIdentifier::ShedLevelDescriptions => write!(f, "shed-level-descriptions"),
            PropertyIdentifier::ShedLevels => write!(f, "shed-levels"),
            PropertyIdentifier::StateDescription => write!(f, "state-description"),
            PropertyIdentifier::DoorAlarmState => write!(f, "door-alarm-state"),
            PropertyIdentifier::DoorExtendedPulseTime => write!(f, "door-extended-pulse-time"),
            PropertyIdentifier::DoorMembers => write!(f, "door-members"),
            PropertyIdentifier::DoorOpenTooLongTime => write!(f, "door-open-too-long-time"),
            PropertyIdentifier::DoorPulseTime => write!(f, "door-pulse-time"),
            PropertyIdentifier::DoorStatus => write!(f, "door-status"),
            PropertyIdentifier::DoorUnlockDelayTime => write!(f, "door-unlock-delay-time"),
            PropertyIdentifier::LockStatus => write!(f, "lock-status"),
            PropertyIdentifier::MaskedAlarmValues => write!(f, "masked-alarm-values"),
            PropertyIdentifier::SecuredAccess => write!(f, "secured-access"),
            PropertyIdentifier::AbsenteeLimit => write!(f, "absentee-limit"),
            PropertyIdentifier::AccessAlarmEvents => write!(f, "access-alarm-events"),
            PropertyIdentifier::AccessDoors => write!(f, "access-doors"),
            PropertyIdentifier::AccessEvent => write!(f, "access-event"),
            PropertyIdentifier::AccessEventAuthenticationFactor => {
                write!(f, "access-event-authentication-factor")
            }
            PropertyIdentifier::AccessEventCredential => write!(f, "access-event-credential"),
            PropertyIdentifier::AccessEventTime => write!(f, "access-event-time"),
            PropertyIdentifier::AccessTransactionEvents => write!(f, "access-transaction-events"),
            PropertyIdentifier::Accompaniment => write!(f, "accompaniment"),
            PropertyIdentifier::AccompanimentTime => write!(f, "accompaniment-time"),
            PropertyIdentifier::ActivationTime => write!(f, "activation-time"),
            PropertyIdentifier::ActiveAuthenticationPolicy => {
                write!(f, "active-authentication-policy")
            }
            PropertyIdentifier::AssignedAccessRights => write!(f, "assigned-access-rights"),
            PropertyIdentifier::AuthenticationFactors => write!(f, "authentication-factors"),
            PropertyIdentifier::AuthenticationPolicyList => write!(f, "authentication-policy-list"),
            PropertyIdentifier::AuthenticationPolicyNames => {
                write!(f, "authentication-policy-names")
            }
            PropertyIdentifier::AuthenticationStatus => write!(f, "authentication-status"),
            PropertyIdentifier::AuthorizationMode => write!(f, "authorization-mode"),
            PropertyIdentifier::BelongsTo => write!(f, "belongs-to"),
            PropertyIdentifier::CredentialDisable => write!(f, "credential-disable"),
            PropertyIdentifier::CredentialStatus => write!(f, "credential-status"),
            PropertyIdentifier::Credentials => write!(f, "credentials"),
            PropertyIdentifier::CredentialsInZone => write!(f, "credentials-in-zone"),
            PropertyIdentifier::DaysRemaining => write!(f, "days-remaining"),
            PropertyIdentifier::EntryPoints => write!(f, "entry-points"),
            PropertyIdentifier::ExitPoints => write!(f, "exit-points"),
            PropertyIdentifier::ExpiryTime => write!(f, "expiry-time"),
            PropertyIdentifier::ExtendedTimeEnable => write!(f, "extended-time-enable"),
            PropertyIdentifier::FailedAttemptEvents => write!(f, "failed-attempt-events"),
            PropertyIdentifier::FailedAttempts => write!(f, "failed-attempts"),
            PropertyIdentifier::FailedAttemptsTime => write!(f, "failed-attempts-time"),
            PropertyIdentifier::LastAccessEvent => write!(f, "last-access-event"),
            PropertyIdentifier::LastAccessPoint => write!(f, "last-access-point"),
            PropertyIdentifier::LastCredentialAdded => write!(f, "last-credential-added"),
            PropertyIdentifier::LastCredentialAddedTime => write!(f, "last-credential-added-time"),
            PropertyIdentifier::LastCredentialRemoved => write!(f, "last-credential-removed"),
            PropertyIdentifier::LastCredentialRemovedTime => {
                write!(f, "last-credential-removed-time")
            }
            PropertyIdentifier::LastUseTime => write!(f, "last-use-time"),
            PropertyIdentifier::Lockout => write!(f, "lockout"),
            PropertyIdentifier::LockoutRelinquishTime => write!(f, "lockout-relinquish-time"),
            PropertyIdentifier::MasterExemption => write!(f, "master-exemption"),
            PropertyIdentifier::MaxFailedAttempts => write!(f, "max-failed-attempts"),
            PropertyIdentifier::Members => write!(f, "members"),
            PropertyIdentifier::MemberOf2 => write!(f, "member-of2"),
            PropertyIdentifier::NegativeAccessRules => write!(f, "negative-access-rules"),
            PropertyIdentifier::NumberOfAuthenticationPolicies => {
                write!(f, "number-of-authentication-policies")
            }
            PropertyIdentifier::OccupancyCount => write!(f, "occupancy-count"),
            PropertyIdentifier::OccupancyCountAdjust => write!(f, "occupancy-count-adjust"),
            PropertyIdentifier::OccupancyCountEnable => write!(f, "occupancy-count-enable"),
            PropertyIdentifier::OccupancyExemption => write!(f, "occupancy-exemption"),
            PropertyIdentifier::OccupancyLowerLimit => write!(f, "occupancy-lower-limit"),
            PropertyIdentifier::OccupancyLowerLimitEnforced => {
                write!(f, "occupancy-lower-limit-enforced")
            }
            PropertyIdentifier::OccupancyState => write!(f, "occupancy-state"),
            PropertyIdentifier::OccupancyUpperLimit => write!(f, "occupancy-upper-limit"),
            PropertyIdentifier::OccupancyUpperLimitEnforced => {
                write!(f, "occupancy-upper-limit-enforced")
            }
            PropertyIdentifier::PassbackExemption => write!(f, "passback-exemption"),
            PropertyIdentifier::PassbackMode => write!(f, "passback-mode"),
            PropertyIdentifier::PassbackTimeout => write!(f, "passback-timeout"),
            PropertyIdentifier::PositiveAccessRules => write!(f, "positive-access-rules"),
            PropertyIdentifier::ReasonForDisable => write!(f, "reason-for-disable"),
            PropertyIdentifier::SupportedFormats => write!(f, "supported-formats"),
            PropertyIdentifier::SupportedFormatClasses => write!(f, "supported-format-classes"),
            PropertyIdentifier::ThreatAuthority => write!(f, "threat-authority"),
            PropertyIdentifier::ThreatLevel => write!(f, "threat-level"),
            PropertyIdentifier::TraceFlag => write!(f, "trace-flag"),
            PropertyIdentifier::TransactionNotificationClass => {
                write!(f, "transaction-notification-class")
            }
            PropertyIdentifier::UserExternalIdentifier => write!(f, "user-external-identifier"),
            PropertyIdentifier::UserInformationReference => write!(f, "user-information-reference"),
            PropertyIdentifier::UserName => write!(f, "user-name"),
            PropertyIdentifier::UserType => write!(f, "user-type"),
            PropertyIdentifier::UsesRemaining => write!(f, "uses-remaining"),
            PropertyIdentifier::ZoneFrom => write!(f, "zone-from"),
            PropertyIdentifier::ZoneTo => write!(f, "zone-to"),
            PropertyIdentifier::AccessEventTag => write!(f, "access-event-tag"),
            PropertyIdentifier::GlobalIdentifier => write!(f, "global-identifier"),
            PropertyIdentifier::VerificationTime => write!(f, "verification-time"),
            PropertyIdentifier::BaseDeviceSecurityPolicy => {
                write!(f, "base-device-security-policy")
            }
            PropertyIdentifier::DistributionKeyRevision => write!(f, "distribution-key-revision"),
            PropertyIdentifier::DoNotHide => write!(f, "do-not-hide"),
            PropertyIdentifier::KeySets => write!(f, "key-sets"),
            PropertyIdentifier::LastKeyServer => write!(f, "last-key-server"),
            PropertyIdentifier::NetworkAccessSecurityPolicies => {
                write!(f, "network-access-security-policies")
            }
            PropertyIdentifier::PacketReorderTime => write!(f, "packet-reorder-time"),
            PropertyIdentifier::SecurityPduTimeout => write!(f, "security-pdu-timeout"),
            PropertyIdentifier::SecurityTimeWindow => write!(f, "security-time-window"),
            PropertyIdentifier::SupportedSecurityAlgorithm => {
                write!(f, "supported-security-algorithm")
            }
            PropertyIdentifier::UpdateKeySetTimeout => write!(f, "update-key-set-timeout"),
            PropertyIdentifier::BackupAndRestoreState => write!(f, "backup-and-restore-state"),
            PropertyIdentifier::BackupPreparationTime => write!(f, "backup-preparation-time"),
            PropertyIdentifier::RestoreCompletionTime => write!(f, "restore-completion-time"),
            PropertyIdentifier::RestorePreparationTime => write!(f, "restore-preparation-time"),
            PropertyIdentifier::BitMask => write!(f, "bit-mask"),
            PropertyIdentifier::BitText => write!(f, "bit-text"),
            PropertyIdentifier::IsUtc => write!(f, "is-utc"),
            PropertyIdentifier::GroupMembers => write!(f, "group-members"),
            PropertyIdentifier::GroupMemberNames => write!(f, "group-member-names"),
            PropertyIdentifier::MemberStatusFlags => write!(f, "member-status-flags"),
            PropertyIdentifier::RequestedUpdateInterval => write!(f, "requested-update-interval"),
            PropertyIdentifier::Resolution2 => write!(f, "resolution2"),
            PropertyIdentifier::CovuPeriod => write!(f, "covu-period"),
            PropertyIdentifier::CovuRecipients => write!(f, "covu-recipients"),
            PropertyIdentifier::EventMessageTexts => write!(f, "event-message-texts"),
            PropertyIdentifier::EventMessageTextsConfig => write!(f, "event-message-texts-config"),
            PropertyIdentifier::EventDetectionEnable => write!(f, "event-detection-enable"),
            PropertyIdentifier::EventAlgorithmInhibit => write!(f, "event-algorithm-inhibit"),
            PropertyIdentifier::EventAlgorithmInhibitRef => {
                write!(f, "event-algorithm-inhibit-ref")
            }
            PropertyIdentifier::TimeDelayNormal => write!(f, "time-delay-normal"),
            PropertyIdentifier::ReliabilityEvaluationInhibit => {
                write!(f, "reliability-evaluation-inhibit")
            }
            PropertyIdentifier::FaultParameters => write!(f, "fault-parameters"),
            PropertyIdentifier::FaultType => write!(f, "fault-type"),
            PropertyIdentifier::LocalForwardingOnly => write!(f, "local-forwarding-only"),
            PropertyIdentifier::ProcessIdentifierFilter => write!(f, "process-identifier-filter"),
            PropertyIdentifier::SubscribedRecipients => write!(f, "subscribed-recipients"),
            PropertyIdentifier::PortFilter => write!(f, "port-filter"),
            PropertyIdentifier::AuthorizationExemptions => write!(f, "authorization-exemptions"),
            PropertyIdentifier::AllowGroupDelayInhibit => write!(f, "allow-group-delay-inhibit"),
            PropertyIdentifier::ChannelNumber => write!(f, "channel-number"),
            PropertyIdentifier::ControlGroups => write!(f, "control-groups"),
            PropertyIdentifier::ExecutionDelay => write!(f, "execution-delay"),
            PropertyIdentifier::LastPriority => write!(f, "last-priority"),
            PropertyIdentifier::WriteStatus => write!(f, "write-status"),
            PropertyIdentifier::PropertyList => write!(f, "property-list"),
            PropertyIdentifier::SerialNumber => write!(f, "serial-number"),
            PropertyIdentifier::BlinkWarnEnable => write!(f, "blink-warn-enable"),
            PropertyIdentifier::DefaultFadeTime => write!(f, "default-fade-time"),
            PropertyIdentifier::DefaultRampRate => write!(f, "default-ramp-rate"),
            PropertyIdentifier::DefaultStepIncrement => write!(f, "default-step-increment"),
            PropertyIdentifier::EgressActive => write!(f, "egress-active"),
            PropertyIdentifier::EgressTime => write!(f, "egress-time"),
            PropertyIdentifier::InProgress => write!(f, "in-progress"),
            PropertyIdentifier::InstantianeousPower => write!(f, "instantianeous-power"),
            PropertyIdentifier::LightingCommand => write!(f, "lighting-command"),
            PropertyIdentifier::LightingCommandDefaultPriority => {
                write!(f, "lighting-command-default-priority")
            }
            PropertyIdentifier::MaxActualValue => write!(f, "max-actual-value"),
            PropertyIdentifier::MinActualValue => write!(f, "min-actual-value"),
            PropertyIdentifier::Power => write!(f, "power"),
            PropertyIdentifier::Transition => write!(f, "transition"),
            PropertyIdentifier::Unknown(v) => write!(f, "unknown({})", v),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ErrorClass
// ─────────────────────────────────────────────────────────────────────────────

/// BACnet error class values (clause 18.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ErrorClass {
    Device,
    Object,
    Property,
    Resources,
    Security,
    Services,
    Vt,
    Communication,
    Unknown(u32),
}

impl From<u32> for ErrorClass {
    fn from(value: u32) -> Self {
        match value {
            0 => ErrorClass::Device,
            1 => ErrorClass::Object,
            2 => ErrorClass::Property,
            3 => ErrorClass::Resources,
            4 => ErrorClass::Security,
            5 => ErrorClass::Services,
            6 => ErrorClass::Vt,
            7 => ErrorClass::Communication,
            v => ErrorClass::Unknown(v),
        }
    }
}

impl From<ErrorClass> for u32 {
    fn from(e: ErrorClass) -> u32 {
        match e {
            ErrorClass::Device => 0,
            ErrorClass::Object => 1,
            ErrorClass::Property => 2,
            ErrorClass::Resources => 3,
            ErrorClass::Security => 4,
            ErrorClass::Services => 5,
            ErrorClass::Vt => 6,
            ErrorClass::Communication => 7,
            ErrorClass::Unknown(v) => v,
        }
    }
}

impl fmt::Display for ErrorClass {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ErrorClass::Device => write!(f, "device"),
            ErrorClass::Object => write!(f, "object"),
            ErrorClass::Property => write!(f, "property"),
            ErrorClass::Resources => write!(f, "resources"),
            ErrorClass::Security => write!(f, "security"),
            ErrorClass::Services => write!(f, "services"),
            ErrorClass::Vt => write!(f, "vt"),
            ErrorClass::Communication => write!(f, "communication"),
            ErrorClass::Unknown(v) => write!(f, "unknown({})", v),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// ErrorCode
// ─────────────────────────────────────────────────────────────────────────────

/// BACnet error code values (clause 18.1).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ErrorCode {
    Other,
    AuthenticationFailed,
    CharacterSetNotSupported,
    CommunicationDisabled,
    ConfigurationInProgress,
    DataTypeNotSupported,
    DuplicateName,
    DuplicateObjectId,
    DynamicCreationNotSupported,
    FileAccessDenied,
    IncompatibleSecurityLevels,
    InconsistentParameters,
    InconsistentSelectionCriterion,
    InvalidArrayIndex,
    InvalidConfigurationData,
    InvalidDataType,
    InvalidFileAccessMethod,
    InvalidFileStartPosition,
    InvalidParamterDataType,
    InvalidTimeStamp,
    KeyGenerationError,
    MissingRequiredParameter,
    NoObjectsOfSpecifiedType,
    NoSpaceForObject,
    NoSpaceToAddListElement,
    NoSpaceToWriteProperty,
    NoVtSessionsAvailable,
    ObjectDeletionNotPermitted,
    ObjectIdentifierAlreadyExists,
    OperationalProblem,
    PasswordFailure,
    ReadAccessDenied,
    SecurityNotSupported,
    ServiceRequestDenied,
    Timeout,
    UnknownObject,
    UnknownProperty,
    UnknownVtClass,
    UnknownVtSession,
    UnsupportedObjectType,
    ValueOutOfRange,
    VtSessionAlreadyClosed,
    VtSessionTerminationFailure,
    WriteAccessDenied,
    CharacterSetRequired,
    InvalidNetworkPort,
    InvalidEventState,
    InvalidTag,
    NetworkDownError,
    RejectBufferFull,
    RejectInconsistentParameters,
    RejectInvalidParameterDataType,
    RejectInvalidTag,
    RejectMissingRequiredParameter,
    RejectParameterOutOfRange,
    RejectTooManyArguments,
    RejectUndefinedEnumeration,
    RejectUnrecognizedService,
    RejectProprietary,
    RejectOther,
    UnknownDevice,
    UnknownRoute,
    ValueNotInitialized,
    InvalidEventType,
    NotConfigured,
    OutOfMemory,
    ValueTooLong,
    AbortBufferOverflow,
    AbortInvalidApduInThisState,
    AbortPreemptedByHigherPriorityTask,
    AbortSegmentationNotSupported,
    AbortProprietary,
    AbortOther,
    InvalidTag2,
    NetworkDown,
    RejectMessageTooLong,
    Unknown(u32),
}

impl From<u32> for ErrorCode {
    fn from(value: u32) -> Self {
        match value {
            0 => ErrorCode::Other,
            1 => ErrorCode::AuthenticationFailed,
            2 => ErrorCode::CharacterSetNotSupported,
            3 => ErrorCode::CommunicationDisabled,
            4 => ErrorCode::ConfigurationInProgress,
            5 => ErrorCode::DataTypeNotSupported,
            6 => ErrorCode::DuplicateName,
            7 => ErrorCode::DuplicateObjectId,
            8 => ErrorCode::DynamicCreationNotSupported,
            9 => ErrorCode::FileAccessDenied,
            10 => ErrorCode::IncompatibleSecurityLevels,
            11 => ErrorCode::InconsistentParameters,
            12 => ErrorCode::InconsistentSelectionCriterion,
            13 => ErrorCode::InvalidArrayIndex,
            14 => ErrorCode::InvalidConfigurationData,
            15 => ErrorCode::InvalidDataType,
            16 => ErrorCode::InvalidFileAccessMethod,
            17 => ErrorCode::InvalidFileStartPosition,
            18 => ErrorCode::InvalidParamterDataType,
            19 => ErrorCode::InvalidTimeStamp,
            20 => ErrorCode::KeyGenerationError,
            21 => ErrorCode::MissingRequiredParameter,
            22 => ErrorCode::NoObjectsOfSpecifiedType,
            23 => ErrorCode::NoSpaceForObject,
            24 => ErrorCode::NoSpaceToAddListElement,
            25 => ErrorCode::NoSpaceToWriteProperty,
            26 => ErrorCode::NoVtSessionsAvailable,
            27 => ErrorCode::ObjectDeletionNotPermitted,
            28 => ErrorCode::ObjectIdentifierAlreadyExists,
            29 => ErrorCode::OperationalProblem,
            30 => ErrorCode::PasswordFailure,
            31 => ErrorCode::ReadAccessDenied,
            32 => ErrorCode::SecurityNotSupported,
            33 => ErrorCode::ServiceRequestDenied,
            34 => ErrorCode::Timeout,
            35 => ErrorCode::UnknownObject,
            36 => ErrorCode::UnknownProperty,
            37 => ErrorCode::UnknownVtClass,
            38 => ErrorCode::UnknownVtSession,
            39 => ErrorCode::UnsupportedObjectType,
            40 => ErrorCode::ValueOutOfRange,
            41 => ErrorCode::VtSessionAlreadyClosed,
            42 => ErrorCode::VtSessionTerminationFailure,
            43 => ErrorCode::WriteAccessDenied,
            44 => ErrorCode::CharacterSetRequired,
            45 => ErrorCode::InvalidNetworkPort,
            46 => ErrorCode::InvalidEventState,
            47 => ErrorCode::InvalidTag,
            48 => ErrorCode::NetworkDownError,
            49 => ErrorCode::RejectBufferFull,
            50 => ErrorCode::RejectInconsistentParameters,
            51 => ErrorCode::RejectInvalidParameterDataType,
            52 => ErrorCode::RejectInvalidTag,
            53 => ErrorCode::RejectMissingRequiredParameter,
            54 => ErrorCode::RejectParameterOutOfRange,
            55 => ErrorCode::RejectTooManyArguments,
            56 => ErrorCode::RejectUndefinedEnumeration,
            57 => ErrorCode::RejectUnrecognizedService,
            58 => ErrorCode::RejectProprietary,
            59 => ErrorCode::RejectOther,
            60 => ErrorCode::UnknownDevice,
            61 => ErrorCode::UnknownRoute,
            62 => ErrorCode::ValueNotInitialized,
            63 => ErrorCode::InvalidEventType,
            64 => ErrorCode::NotConfigured,
            65 => ErrorCode::OutOfMemory,
            66 => ErrorCode::ValueTooLong,
            67 => ErrorCode::AbortBufferOverflow,
            68 => ErrorCode::AbortInvalidApduInThisState,
            69 => ErrorCode::AbortPreemptedByHigherPriorityTask,
            70 => ErrorCode::AbortSegmentationNotSupported,
            71 => ErrorCode::AbortProprietary,
            72 => ErrorCode::AbortOther,
            73 => ErrorCode::InvalidTag2,
            74 => ErrorCode::NetworkDown,
            75 => ErrorCode::RejectMessageTooLong,
            v => ErrorCode::Unknown(v),
        }
    }
}

impl From<ErrorCode> for u32 {
    fn from(e: ErrorCode) -> u32 {
        match e {
            ErrorCode::Other => 0,
            ErrorCode::AuthenticationFailed => 1,
            ErrorCode::CharacterSetNotSupported => 2,
            ErrorCode::CommunicationDisabled => 3,
            ErrorCode::ConfigurationInProgress => 4,
            ErrorCode::DataTypeNotSupported => 5,
            ErrorCode::DuplicateName => 6,
            ErrorCode::DuplicateObjectId => 7,
            ErrorCode::DynamicCreationNotSupported => 8,
            ErrorCode::FileAccessDenied => 9,
            ErrorCode::IncompatibleSecurityLevels => 10,
            ErrorCode::InconsistentParameters => 11,
            ErrorCode::InconsistentSelectionCriterion => 12,
            ErrorCode::InvalidArrayIndex => 13,
            ErrorCode::InvalidConfigurationData => 14,
            ErrorCode::InvalidDataType => 15,
            ErrorCode::InvalidFileAccessMethod => 16,
            ErrorCode::InvalidFileStartPosition => 17,
            ErrorCode::InvalidParamterDataType => 18,
            ErrorCode::InvalidTimeStamp => 19,
            ErrorCode::KeyGenerationError => 20,
            ErrorCode::MissingRequiredParameter => 21,
            ErrorCode::NoObjectsOfSpecifiedType => 22,
            ErrorCode::NoSpaceForObject => 23,
            ErrorCode::NoSpaceToAddListElement => 24,
            ErrorCode::NoSpaceToWriteProperty => 25,
            ErrorCode::NoVtSessionsAvailable => 26,
            ErrorCode::ObjectDeletionNotPermitted => 27,
            ErrorCode::ObjectIdentifierAlreadyExists => 28,
            ErrorCode::OperationalProblem => 29,
            ErrorCode::PasswordFailure => 30,
            ErrorCode::ReadAccessDenied => 31,
            ErrorCode::SecurityNotSupported => 32,
            ErrorCode::ServiceRequestDenied => 33,
            ErrorCode::Timeout => 34,
            ErrorCode::UnknownObject => 35,
            ErrorCode::UnknownProperty => 36,
            ErrorCode::UnknownVtClass => 37,
            ErrorCode::UnknownVtSession => 38,
            ErrorCode::UnsupportedObjectType => 39,
            ErrorCode::ValueOutOfRange => 40,
            ErrorCode::VtSessionAlreadyClosed => 41,
            ErrorCode::VtSessionTerminationFailure => 42,
            ErrorCode::WriteAccessDenied => 43,
            ErrorCode::CharacterSetRequired => 44,
            ErrorCode::InvalidNetworkPort => 45,
            ErrorCode::InvalidEventState => 46,
            ErrorCode::InvalidTag => 47,
            ErrorCode::NetworkDownError => 48,
            ErrorCode::RejectBufferFull => 49,
            ErrorCode::RejectInconsistentParameters => 50,
            ErrorCode::RejectInvalidParameterDataType => 51,
            ErrorCode::RejectInvalidTag => 52,
            ErrorCode::RejectMissingRequiredParameter => 53,
            ErrorCode::RejectParameterOutOfRange => 54,
            ErrorCode::RejectTooManyArguments => 55,
            ErrorCode::RejectUndefinedEnumeration => 56,
            ErrorCode::RejectUnrecognizedService => 57,
            ErrorCode::RejectProprietary => 58,
            ErrorCode::RejectOther => 59,
            ErrorCode::UnknownDevice => 60,
            ErrorCode::UnknownRoute => 61,
            ErrorCode::ValueNotInitialized => 62,
            ErrorCode::InvalidEventType => 63,
            ErrorCode::NotConfigured => 64,
            ErrorCode::OutOfMemory => 65,
            ErrorCode::ValueTooLong => 66,
            ErrorCode::AbortBufferOverflow => 67,
            ErrorCode::AbortInvalidApduInThisState => 68,
            ErrorCode::AbortPreemptedByHigherPriorityTask => 69,
            ErrorCode::AbortSegmentationNotSupported => 70,
            ErrorCode::AbortProprietary => 71,
            ErrorCode::AbortOther => 72,
            ErrorCode::InvalidTag2 => 73,
            ErrorCode::NetworkDown => 74,
            ErrorCode::RejectMessageTooLong => 75,
            ErrorCode::Unknown(v) => v,
        }
    }
}

impl fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ErrorCode::Other => write!(f, "other"),
            ErrorCode::AuthenticationFailed => write!(f, "authentication-failed"),
            ErrorCode::CharacterSetNotSupported => write!(f, "character-set-not-supported"),
            ErrorCode::CommunicationDisabled => write!(f, "communication-disabled"),
            ErrorCode::ConfigurationInProgress => write!(f, "configuration-in-progress"),
            ErrorCode::DataTypeNotSupported => write!(f, "data-type-not-supported"),
            ErrorCode::DuplicateName => write!(f, "duplicate-name"),
            ErrorCode::DuplicateObjectId => write!(f, "duplicate-object-id"),
            ErrorCode::DynamicCreationNotSupported => write!(f, "dynamic-creation-not-supported"),
            ErrorCode::FileAccessDenied => write!(f, "file-access-denied"),
            ErrorCode::IncompatibleSecurityLevels => write!(f, "incompatible-security-levels"),
            ErrorCode::InconsistentParameters => write!(f, "inconsistent-parameters"),
            ErrorCode::InconsistentSelectionCriterion => {
                write!(f, "inconsistent-selection-criterion")
            }
            ErrorCode::InvalidArrayIndex => write!(f, "invalid-array-index"),
            ErrorCode::InvalidConfigurationData => write!(f, "invalid-configuration-data"),
            ErrorCode::InvalidDataType => write!(f, "invalid-data-type"),
            ErrorCode::InvalidFileAccessMethod => write!(f, "invalid-file-access-method"),
            ErrorCode::InvalidFileStartPosition => write!(f, "invalid-file-start-position"),
            ErrorCode::InvalidParamterDataType => write!(f, "invalid-paramter-data-type"),
            ErrorCode::InvalidTimeStamp => write!(f, "invalid-time-stamp"),
            ErrorCode::KeyGenerationError => write!(f, "key-generation-error"),
            ErrorCode::MissingRequiredParameter => write!(f, "missing-required-parameter"),
            ErrorCode::NoObjectsOfSpecifiedType => write!(f, "no-objects-of-specified-type"),
            ErrorCode::NoSpaceForObject => write!(f, "no-space-for-object"),
            ErrorCode::NoSpaceToAddListElement => write!(f, "no-space-to-add-list-element"),
            ErrorCode::NoSpaceToWriteProperty => write!(f, "no-space-to-write-property"),
            ErrorCode::NoVtSessionsAvailable => write!(f, "no-vt-sessions-available"),
            ErrorCode::ObjectDeletionNotPermitted => write!(f, "object-deletion-not-permitted"),
            ErrorCode::ObjectIdentifierAlreadyExists => {
                write!(f, "object-identifier-already-exists")
            }
            ErrorCode::OperationalProblem => write!(f, "operational-problem"),
            ErrorCode::PasswordFailure => write!(f, "password-failure"),
            ErrorCode::ReadAccessDenied => write!(f, "read-access-denied"),
            ErrorCode::SecurityNotSupported => write!(f, "security-not-supported"),
            ErrorCode::ServiceRequestDenied => write!(f, "service-request-denied"),
            ErrorCode::Timeout => write!(f, "timeout"),
            ErrorCode::UnknownObject => write!(f, "unknown-object"),
            ErrorCode::UnknownProperty => write!(f, "unknown-property"),
            ErrorCode::UnknownVtClass => write!(f, "unknown-vt-class"),
            ErrorCode::UnknownVtSession => write!(f, "unknown-vt-session"),
            ErrorCode::UnsupportedObjectType => write!(f, "unsupported-object-type"),
            ErrorCode::ValueOutOfRange => write!(f, "value-out-of-range"),
            ErrorCode::VtSessionAlreadyClosed => write!(f, "vt-session-already-closed"),
            ErrorCode::VtSessionTerminationFailure => write!(f, "vt-session-termination-failure"),
            ErrorCode::WriteAccessDenied => write!(f, "write-access-denied"),
            ErrorCode::CharacterSetRequired => write!(f, "character-set-required"),
            ErrorCode::InvalidNetworkPort => write!(f, "invalid-network-port"),
            ErrorCode::InvalidEventState => write!(f, "invalid-event-state"),
            ErrorCode::InvalidTag => write!(f, "invalid-tag"),
            ErrorCode::NetworkDownError => write!(f, "network-down-error"),
            ErrorCode::RejectBufferFull => write!(f, "reject-buffer-full"),
            ErrorCode::RejectInconsistentParameters => write!(f, "reject-inconsistent-parameters"),
            ErrorCode::RejectInvalidParameterDataType => {
                write!(f, "reject-invalid-parameter-data-type")
            }
            ErrorCode::RejectInvalidTag => write!(f, "reject-invalid-tag"),
            ErrorCode::RejectMissingRequiredParameter => {
                write!(f, "reject-missing-required-parameter")
            }
            ErrorCode::RejectParameterOutOfRange => write!(f, "reject-parameter-out-of-range"),
            ErrorCode::RejectTooManyArguments => write!(f, "reject-too-many-arguments"),
            ErrorCode::RejectUndefinedEnumeration => write!(f, "reject-undefined-enumeration"),
            ErrorCode::RejectUnrecognizedService => write!(f, "reject-unrecognized-service"),
            ErrorCode::RejectProprietary => write!(f, "reject-proprietary"),
            ErrorCode::RejectOther => write!(f, "reject-other"),
            ErrorCode::UnknownDevice => write!(f, "unknown-device"),
            ErrorCode::UnknownRoute => write!(f, "unknown-route"),
            ErrorCode::ValueNotInitialized => write!(f, "value-not-initialized"),
            ErrorCode::InvalidEventType => write!(f, "invalid-event-type"),
            ErrorCode::NotConfigured => write!(f, "not-configured"),
            ErrorCode::OutOfMemory => write!(f, "out-of-memory"),
            ErrorCode::ValueTooLong => write!(f, "value-too-long"),
            ErrorCode::AbortBufferOverflow => write!(f, "abort-buffer-overflow"),
            ErrorCode::AbortInvalidApduInThisState => write!(f, "abort-invalid-apdu-in-this-state"),
            ErrorCode::AbortPreemptedByHigherPriorityTask => {
                write!(f, "abort-preempted-by-higher-priority-task")
            }
            ErrorCode::AbortSegmentationNotSupported => {
                write!(f, "abort-segmentation-not-supported")
            }
            ErrorCode::AbortProprietary => write!(f, "abort-proprietary"),
            ErrorCode::AbortOther => write!(f, "abort-other"),
            ErrorCode::InvalidTag2 => write!(f, "invalid-tag2"),
            ErrorCode::NetworkDown => write!(f, "network-down"),
            ErrorCode::RejectMessageTooLong => write!(f, "reject-message-too-long"),
            ErrorCode::Unknown(v) => write!(f, "unknown({})", v),
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Tests
// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_property_identifier_known_round_trip() {
        assert_eq!(
            PropertyIdentifier::from(85u32),
            PropertyIdentifier::PresentValue
        );
        assert_eq!(u32::from(PropertyIdentifier::PresentValue), 85u32);
    }

    #[test]
    fn test_property_identifier_unknown_round_trip() {
        assert_eq!(
            PropertyIdentifier::from(9999u32),
            PropertyIdentifier::Unknown(9999)
        );
        assert_eq!(u32::from(PropertyIdentifier::Unknown(9999)), 9999u32);
    }

    #[test]
    fn test_error_class_known_round_trip() {
        assert_eq!(ErrorClass::from(2u32), ErrorClass::Property);
        assert_eq!(u32::from(ErrorClass::Property), 2u32);
    }

    #[test]
    fn test_error_class_unknown_round_trip() {
        assert_eq!(ErrorClass::from(9999u32), ErrorClass::Unknown(9999));
        assert_eq!(u32::from(ErrorClass::Unknown(9999)), 9999u32);
    }

    #[test]
    fn test_error_code_known_round_trip() {
        assert_eq!(ErrorCode::from(36u32), ErrorCode::UnknownProperty);
        assert_eq!(u32::from(ErrorCode::UnknownProperty), 36u32);
    }

    #[test]
    fn test_error_code_unknown_round_trip() {
        assert_eq!(ErrorCode::from(9999u32), ErrorCode::Unknown(9999));
        assert_eq!(u32::from(ErrorCode::Unknown(9999)), 9999u32);
    }
}
